### ISSUE TITLE
Chris' Cutscene Head bug

### ISSUE THREAD

**Issue by pakjuaan** [HenryOfCarim/albam_reloaded#13]
Hi, I was using the ablam_reloaded 0.3.5 add-on and I was trying to mod Chris' cutscene head.

This is the default .arc file of Chris' cutscene head 
![re5dx9 2022-08-09 23-15-17](https://user-images.githubusercontent.com/57705784/183689437-a49d700f-2349-4a9f-92cc-3ef20f7a5645.png)

This is what Chris' cutscene head look like in cutscenes after importing the .arc file in blender and exporting it.
![re5dx9 2022-08-09 23-13-37](https://user-images.githubusercontent.com/57705784/183689570-399b3eca-a75b-4a51-af64-53819d4b3f44.png)

Note: I haven't even modified anything on the .arc file yet, I just simply imported it on blender and exported it to see what it will look like in the game

**Comment by HenryOfCarim** [comment]
This is a well-known bug,  how to deal with it is described in Wiki https://github.com/HenryOfCarim/albam_reloaded/wiki/How-to-use#double-heads-in-cut-scenes

You should set  unk_render_group_index to 0 for each mesh

**Comment by pakjuaan** [comment]
Tried, setting the render group indexes of all cutscene meshes to 0. It kinda worked now thank you very much! Just one more thing, is there some sort of cheat sheet for all render group indexes for the models?

**Comment by HenryOfCarim** [comment]
No, we didn't make it because you can always click on an imported mesh and see the render group. They have no use in the game except hiding\showing certain parts during cut-scenes and finishing moves.
