### ISSUE TITLE
Custom Mesh Export bug

### ISSUE THREAD

**Issue by pakjuaan** [HenryOfCarim/albam_reloaded#15]
Hi! Tried exporting Chris Heavy Metal with a custom mesh, but this was the result
![image](https://user-images.githubusercontent.com/57705784/215012157-79f3bf17-c64e-4923-a4e8-21f9d2f16299.png)

Any idea why? :(

**Comment by pakjuaan** [comment]
Is there a face count limit if I may ask?

**Comment by HenryOfCarim** [comment]
Albam supports only triangulated meshes, this bug is because of quads.

**Comment by pakjuaan** [comment]
I see, that's why. Thanks so much! Now it all makes sense now. Will give triangulating the faces a shot and give an update if it worked
