### ISSUE TITLE
Supported Blender version dependent on Python version.

### ISSUE THREAD

**Issue by papabirb** [HenryOfCarim/albam_reloaded#17]
I attempted to do a basic import -> export of Chris Costume 1 with no changes to learn how to use the addon, but all attempts at exporting had an error that ended in " AttributeError: module 'math' has no attribute 'dist' ". This is apparently because of the Python version bundled with Blender, as [Python versions before 3.8 did not support "dist".](https://stackoverflow.com/questions/73190452/attributeerror-module-math-has-no-attribute-dist)

The version of Blender I was using was 2.92, one version below the tested version of 2.93. The version of Python bundled with 2.92 is Python version 3.7, the one right before "dist" is added to "math".

The Python version bundled with Blender 2.93 is Python version 3.9, the version right after "dist" is added.

Therefore, unless the user specifically updates the Python version their Blender is using, by default your addon only works from 2.93 up, not 2.80 up.

**Comment by Brachi** [comment]
Thanks for the report.

I think it might be easy to  backport that math.dist function to support 2.92 at least, but I wonder if it's worth it given that 2.93 it's an LTS release. 

Any reason in particular you need to use 2.92?

At least the README has to be updated, so I will leave this open for now.

**Comment by papabirb** [comment]
No, I personally have no reason in particular for using version 2.92. It was simply what I had installed at the time that I found your addon, and I thought it would work based on the README and being so close to the version that you tested it on. Since 2.80+ is a lot of versions, I wanted to report my experience for clarity.

**Comment by HenryOfCarim** [comment]
Fixed in 0.3.8
