### ISSUE TITLE
Error when exporting model

### ISSUE THREAD

**Issue by ninjafox370** [HenryOfCarim/albam_reloaded#21]
I'm trying to export a model but I'm getting this error: 
![Screenshot 2023-07-25 122915](https://github.com/HenryOfCarim/albam_reloaded/assets/140537869/c26a770f-7732-45f1-8f5a-c5bff0051d3a)

**Comment by HenryOfCarim** [comment]
Are you sure your textures are correct? The albam works only with dds textures with an enabled mipmaps flag.

**Comment by ninjafox370** [comment]
Thank you. I fixed that but now Chris is just invisible.
![Screenshot 2023-07-25 154151](https://github.com/HenryOfCarim/albam_reloaded/assets/140537869/b7a726f7-cb73-4d1e-81e1-8631e69ec461)

**Comment by HenryOfCarim** [comment]
You probably didn't apply transforms, so the model is too big, for checking you can import your modded arc, it probably doesn't look correct

**Comment by ninjafox370** [comment]
I tried switching models but now I'm getting this error: 
![Screenshot 2023-07-25 190555](https://github.com/HenryOfCarim/albam_reloaded/assets/140537869/4ea622cb-addb-4424-95a5-4970be61c37b)

**Comment by HenryOfCarim** [comment]
Your vertex group names don't match with the bone names https://youtu.be/4xn2cnZM4L0

**Comment by ninjafox370** [comment]
What about this one? 
![Screenshot 2023-07-26 163102](https://github.com/HenryOfCarim/albam_reloaded/assets/140537869/09498018-9589-4ea3-8828-0858f47190c3)

**Comment by HenryOfCarim** [comment]
Wrong vertex group name, the addon couldn't find it among bones. You can ask questions on our discord channel in the "support" section. Github issues are more about problems with albam itself [https://discord.gg/69sphky9UX](url)
