### ISSUE TITLE
Errors upon installing and importing

### ISSUE THREAD

**Issue by many-bees** [HenryOfCarim/albam_reloaded#32]
I don't know if it's something wrong with my install of Blender or what but I tried installing it in several different versions but no luck. Whenever I install it I get this error:
![Install error](https://github.com/user-attachments/assets/922aafd3-f71f-47e5-8790-91fc2a019d10)

Trying to enable it gives me this error:
![enable error](https://github.com/user-attachments/assets/6061c3d5-0d65-4533-9e10-943494773524)

There are previous times when I was able to install it, (though I ended up uninstalling for troubleshooting purposes) and upon tring to import a .arc file it just imported an empty and gave me this error:
![import error](https://github.com/user-attachments/assets/b952ccf6-16e7-4828-8bb1-a2ab55075afb)

I've tried asking other people who use this tool for help but so far nobody's been able to figure out what's wrong. I figure someone here might have a better idea of what these errors mean and how I can fix them.

**Comment by HenryOfCarim** [comment]
Albam reloaded as the description says works only for Blender 2.8-3.6 version. You are using 4.2,  only redux version got 4+ support but it's a different thing and it's still in alpha testing

**Comment by many-bees** [comment]
> Albam reloaded as the description says works only for Blender 2.8-3.6 version. You are using 4.2, only redux version got 4+ support but it's a different thing and it's still in alpha testing

I was able to install/enable it in 3.6 but upon trying to import a .arc I got this
![import error 3 6](https://github.com/user-attachments/assets/9507b48a-0f9c-4c04-a63a-985ccc75cfd0)

**Comment by HenryOfCarim** [comment]
What arc are you trying to import?

**Comment by many-bees** [comment]
em0a.arc from REHD

**Comment by HenryOfCarim** [comment]
Albam reloaded works only with RE5, for REHD you need Albam redux, you can get it the `#development` section in our discord server, or build yourself from this repo https://github.com/Brachi/albam

**Comment by many-bees** [comment]
Do you have a link to the Discord or to a tutorial on how to build it?

**Comment by HenryOfCarim** [comment]
Discord link in the Contacts section
https://github.com/HenryOfCarim/albam_reloaded

To build redux you need to download the code as a zip, unpack it, and inside the unpacked folder pack `Albam` folder as a zip archive, it will work as an addon for Blender.

**Comment by many-bees** [comment]
Oh my god it worked thank you so much 😭
![image](https://github.com/user-attachments/assets/6b0586a9-5d14-49b8-b061-41da07673de0)
